### ISSUE TITLE
scaling_max_freq: No such file or directory

### ISSUE THREAD

**Issue by davidjmstewart** [nolanlawson/fuite#123]
I am trying to integrate `fuite` as part of a new project's CI/CD workflow, however the program does not appear to be starting. 

```
Run npm run vite & npx fuite http://localhost:1420 --output fuite-report.json > fuite-log.txt

> vue-project@0.0.0 vite
> vite

env variable DEV_HOST not specified

  VITE v5.[4](https://github.com/CreativeLightingAdmin/SpektraPlus/actions/runs/13003916320/job/36267418322#step:7:5).10  ready in 96[5](https://github.com/CreativeLightingAdmin/SpektraPlus/actions/runs/13003916320/job/36267418322#step:7:6) ms

  ➜  Local:   http://localhost:1420/
  ➜  Network: http://10.1.0.71:1420/
  ➜  Vue DevTools: Open http://localhost:1420/__devtools__/ as a separate window
  ➜  Vue DevTools: Press Alt(⌥)+Shift(⇧)+D in App to toggle the Vue DevTools

npm warn exec The following package was not found and will be installed: fuite@5.0.5
Error: Failed to launch the browser process!
[2189:2189:0128/050135.15375[6](https://github.com/CreativeLightingAdmin/SpektraPlus/actions/runs/13003916320/job/36267418322#step:7:7):FATAL:zygote_host_impl_linux.cc(12[8](https://github.com/CreativeLightingAdmin/SpektraPlus/actions/runs/13003916320/job/36267418322#step:7:9))] No usable sandbox! If you are running on Ubuntu 23.10+ or another Linux distro that has disabled unprivileged user namespaces with AppArmor, see https://chromium.googlesource.com/chromium/src/+/main/docs/security/apparmor-userns-restrictions.md. Otherwise see https://chromium.googlesource.com/chromium/src/+/main/docs/linux/suid_sandbox_development.md for more information on developing with the (older) SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
[0128/050135.161200:ERROR:file_io_posix.cc(145)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)
[0128/050135.16123[9](https://github.com/CreativeLightingAdmin/SpektraPlus/actions/runs/13003916320/job/36267418322#step:7:10):ERROR:file_io_posix.cc(145)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2)


TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at ChildProcess.onClose (file:///home/runner/.npm/_npx/4f0bae50eb4a6363/node_modules/@puppeteer/browsers/lib/esm/launch.js:303:24)
    at ChildProcess.emit (node:events:536:35)
    at ChildProcess._handle.onexit (node:internal/child_process:293:[12](https://github.com/CreativeLightingAdmin/SpektraPlus/actions/runs/13003916320/job/36267418322#step:7:13))
Error: Process completed with exit code 1.
```

Full workflow file:

```
name: Profiling

on:
  push:
    branches:
      - main
      - '*release*'
  pull_request:
    branches:
      - main
      - '*release*'
jobs:
  run-fuite:
    name: run basic memory leak detection
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build capacitor-disk plugin
        run: cd capacitor-disk && npm ci && npm run build
      - name: Build capacitor-plugin-networking plugin
        run: cd capacitor-plugin-networking && npm ci && npm run build
      - name: Do basic memory leak check of the UI
        run: npm run vite & npx fuite http://localhost:1420 --output fuite-report.json > fuite-log.txt
      - name: Save Fuite Report
        if: success()
        run: |
          mkdir -p fuite-reports
          mv fuite-report.json fuite-reports/
          mv fuite-log.txt fuite-reports/
      - name: Upload Fuite Report
        uses: actions/upload-artifact@v4
        with:
          name: fuite-report
          path: fuite-reports/
```
